name: extensions
version: 0.3.1
description: >-
  APIs for commonly used programming patterns and utilities, 
  such as dependency injection, logging, and configuration.
repository: https://www.github.com/jamiewest/extensions
issue_tracker: https://github.com/jamiewest/extensions/issues?q=is%3Aissue+is%3Aopen+label%3Aextensions

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.1
  collection: ^1.15.0
  tuple: ^2.0.0
  uuid: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
