name: extensions
version: 0.3.16
description: >-
  A set of APIs for commonly used programming patterns and utilities, 
  such as dependency injection, logging, and configuration.
repository: https://www.github.com/jamiewest/extensions
issue_tracker: https://github.com/jamiewest/extensions/issues?q=is%3Aissue+is%3Aopen+label%3Aextensions

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  async: ^2.8.2
  characters: ^1.4.0
  collection: ^1.16.0
  cross_file: ^0.3.5+1
  file: ^7.0.0
  glob: ^2.1.2
  http: ^1.2.0
  path: ^1.8.1
  uuid: ^4.5.2
  watcher: ^1.0.1
  xml: ^6.6.1

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  test: ^1.26.3
